version: "3.9"

services:
  api:
    build:
      context: .
    volumes:
      - ./.env:/app/.env
    depends_on:
      pg:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

  migrations:
    build:
      context: .
    volumes:
      - ./.env:/app/.env
    depends_on:
      pg:
        condition: service_healthy
    command: python manage.py migrate


  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todolist_app
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
