# Generated by Django 4.1.7 on 2023-04-04 19:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_alter_goal_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата последнего обновления'),
            preserve_default=False,
        ),
    ]
