name: Build and deploy wokflow
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: docker build
        run: docker build -t saixfix/todo_saixfix_app:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker login
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USER_NAME }} --password-stdin
      - name: docker push
        run: docker push saixfix/todo_saixfix_app:$GITHUB_REF_NAME-$GITHUB_RUN_ID
